# Generated by Django 4.2.7 on 2023-12-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.TextField(max_length=50)),
                ('precio', models.IntegerField(max_length=4)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
